//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winning.DownLoad.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8086/api/rims")]
        public string weburl {
            get {
                return ((string)(this["weburl"]));
            }
            set {
                this["weburl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fKti04vHK0LqBv2mqFCEnj+LbEBG2haG0+Kfe/xTdTTl2xM2IBQWg9z1p+q2UGYCFOz8LDdMTaS0x/tBU" +
            "/Fo62TNX6vWnl+q2NuCWO5pwryifsyWvJDEEmC6rqshDE07BbvxjX+23mZDcfvbX5QjUw==")]
        public string getPatEx {
            get {
                return ((string)(this["getPatEx"]));
            }
            set {
                this["getPatEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fKti04vHK0LqBv2mqFCEnj+LbEBG2haG0+Kfe/xTdTTl2xM2IBQWg9z1p+q2UGYCFOz8LDdMTaS0x/tBU" +
            "/Fo68JTcKkGuFBsnisn7i20sKr8Na2vXpRs3GohL6E3TeVfLQ0uW9WToOke5jA8a1uAUtf8Pw2iUgl4")]
        public string getJzPatEx {
            get {
                return ((string)(this["getJzPatEx"]));
            }
            set {
                this["getJzPatEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0/30 * * * * ? *")]
        public string getJzXmEx {
            get {
                return ((string)(this["getJzXmEx"]));
            }
            set {
                this["getJzXmEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0/30 * * * * ? *")]
        public string getJzZdEx {
            get {
                return ((string)(this["getJzZdEx"]));
            }
            set {
                this["getJzZdEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fKti04vHK0LqBv2mqFCEnof3GLVr7Gciwne2+UINEPx7EVJAs4Gfbl8gsOroAHlcQqMKcxhIlcqT3O3+G" +
            "9yiNcj7TMdAjz43HZfSGixx3jGr9G+5n9M0itwaNit1Ah0kJh6RdWhBULGUk0rM/brJXQ==")]
        public string contr_rims {
            get {
                return ((string)(this["contr_rims"]));
            }
            set {
                this["contr_rims"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fKti04vHK0LqBv2mqFCEnof3GLVr7Gciwne2+UINEPx7EVJAs4Gfbl8gsOroAHlcQqMKcxhIlcqT3O3+G" +
            "9yiNcj7TMdAjz43HZfSGixx3jGr9G+5n9M0itwaNit1Ah0kJh6RdWhBULGUk0rM/brJXQ==")]
        public string contr_common {
            get {
                return ((string)(this["contr_common"]));
            }
            set {
                this["contr_common"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2d4b181d-f4a2-4c85-bf05-0812c437fb6e")]
        public string uid {
            get {
                return ((string)(this["uid"]));
            }
            set {
                this["uid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8f26f8e2-f95d-4f92-a9d9-37383c779fe5")]
        public string appSecret {
            get {
                return ((string)(this["appSecret"]));
            }
            set {
                this["appSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DevExpress Style")]
        public string theme {
            get {
                return ((string)(this["theme"]));
            }
            set {
                this["theme"] = value;
            }
        }
    }
}
